### ISSUE TITLE
Can't start Mopidy (No such image: hassioaddons/mopidy-armv7:latest)

### ISSUE THREAD

**Issue by TychoWerner** [hassio-addons/addon-mopidy#10]
# Problem/Motivation

> I tried to use Mopidy, it seems like the install go thru but when I want to start it doesn't actually start. The Start button doesn't go away and the logs don't get filled at the bottom, even with a refresh.

## Expected behavior

> I excpected Mopidy to start and become available on the Ingress.

## Actual behavior

> Mopidy didn't start and when I looked in the logs of Mopidy there was nothing. And in the Hass.io > System I saw this line:
`19-06-09 19:42:40 ERROR (SyncWorker_15) [hassio.docker] Can't create container from addon_40817795_mopidy: 404 Client Error: Not Found ("No such image: hassioaddons/mopidy-armv7:latest")`

## Steps to reproduce

> I added the repository for the edge addons and used the interface as normal to install; not changed any settings and this happens.

## Proposed changes

> It seems like a image file is not available from the addons store. maybe due to the hassioaddons/mopidy not being hassio-addons. But I am not sure about that.

Specs:

Hostname | hassio
System | HassOS 2.12
Deployment | production
Version | 166
Latest version | 166
Raspberry Pi 3B(+) I believe.

**Comment by frenck** [comment]
This indicates a diskspace or download issue. I've verified that the images have been deployed to dockerhub correctly.

Also, our release tools verify that as well, if that fails, the release never happens.
