### ISSUE TITLE
Issue with Sound

### ISSUE THREAD

**Issue by feradelectronics** [hassio-addons/addon-mopidy#102]
# Problem/Motivation
Trying to play mp3 audio file on HA.  Not working as expected

## Expected behavior
Clear Sound

## Actual behavior
Sound is very distorted, chopping and non ending (continuous)

## Steps to reproduce
HA installed on Win10 with VBox and vdi image

## Proposed changes
Not sure.  Any suggestions/changes appreciated to resolve this.  This feature is very important to me for many different scenarios.
Thanks in advance.

**Comment by brammittendorff** [comment]
Trying to play mp3 audio file on HA. Not working as expected what is your config and what are you trying to do?

**Comment by feradelectronics** [comment]
Hi Bram,

 

Thanks for getting back to me.  In reality all I am doing is trying to play a sound (mp3 file) on the system speaker (headphone or speakers) that HA is installed when an event is triggered.  It used to work great prior to Fall 2020.

 

Originally I had installed  mopidy with bestlibre repository.  It had quit working because of some HA updates.  Then I found out that bestlibre was no longer supporting mopidy add on.  I later found this mopidy addon being developed on the community edge repo and wanted to try it. In a general sense I know it is close but not usable because the sound played is very distorted, choppy and wont end properly. I am not sure how to resolve this other than thinking it may be setup or a programming issue.

 

I have tried mopidy on a RPi3 and RPi4 both 32bit and 64bit installations.  Also I have it installed on a Windows 10, VirtualBox VDI installation.  All with the same results.  If there is any way to fix this it would be greatly appreciated.  

 

Also, I would like to play a local file installed on the HA system without having to use internet access. For example I would like to use something like media_content_id: “Local/sounds/Sound.mp3” from the media or shared folders on the HA installation.:

service: media_player.play_media

data:

              media_content_id: 'https://mysite.com:8123/local/sounds/Sound.mp3'

              media_content_type: music

target:

              entity_id: media_player.speaker

 

 

 

Configuration:

system_packages: []

python_packages: []

settings:

  - name: file/enabled

    value: 'true'

  - name: file/media_dirs

    value: /share/mopidy/media

 

Network:

Defaults 

 

Log:

 

Thanks again,  If you need anything else from me please let me know.

Scott

**Comment by feradelectronics** [comment]
I get the following errors:

 

21-03-12 16:48:23 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/kanboard/config.json: required key not provided @ data['arch']. Got None

21-03-12 16:48:23 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Mopidy

21-03-12 16:48:23 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/mopidy_alpine/config.json: required key not provided @ data['arch']. Got None

21-03-12 16:48:23 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/53caca22/nextcloud/config.json: required key not provided @ data['arch']. Got None

21-03-12 16:48:23 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'after' is deprecated. Please report this to the maintainer of Calibre Web

21-03-12 16:48:23 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of snapcast-client

21-03-12 16:48:23 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'after' is deprecated. Please report this to the maintainer of Calibre Web Comics

21-03-12 16:48:23 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of Mopidy

**Comment by brammittendorff** [comment]
I will dive into this soon.
