### ISSUE TITLE
Mopidy Addon not available in the community repo

### ISSUE THREAD

**Issue by fjfricke** [hassio-addons/addon-mopidy#11]
# Problem/Motivation

> This addon is not available in the community addon.

## Expected behavior

> Should be available.

## Proposed changes

> Please add a new instruction on how to install this addon. I can't find out how to install it.

**Comment by frenck** [comment]
Uuuh... have you seen this?

![image](https://user-images.githubusercontent.com/195327/59614425-07a96100-9121-11e9-8d03-4fffb15e6e3f.png)

It isn't released yet. Thank you for your interest.

**Comment by frenck** [comment]
Oh also duplicate of #8, it helps to look at previous issues raised.
Would have spared you the time to create this issue and the PR.
