### ISSUE TITLE
Mopidy-Iris access from external SSL URL 

### ISSUE THREAD

**Issue by grunjol** [hassio-addons/addon-mopidy#120]
# Problem/Motivation

When accessing the mopidy web iris UI from an external secure (SSL) URL the system complains with a CORS access error.

## Expected behavior

Access the Iris web module

## Actual behavior

Can not connect with Iris when using external URL using mod_proxy.

## Steps to reproduce

Accessing the mopidy iris UI with https://external.duckdns.org 

## Proposed changes

A workaround is manually add the external interface in http/allowed_origins settings
```  
- name: http/allowed_origins
  value: 'external.duckdns.org:443'
```
A proper fix could be add the external URL in the config on boot

**Comment by brammittendorff** [comment]
> # Problem/Motivation
> When accessing the mopidy web iris UI from an external secure (SSL) URL the system complains with a CORS access error.
> 
> ## Expected behavior
> Access the Iris web module
> 
> ## Actual behavior
> Can not connect with Iris when using external URL using mod_proxy.
> 
> ## Steps to reproduce
> Accessing the mopidy iris UI with https://external.duckdns.org
> 
> ## Proposed changes
> A workaround is manually add the external interface in http/allowed_origins settings
> 
> ```
> - name: http/allowed_origins
>   value: 'external.duckdns.org:443'
> ```
> 
> A proper fix could be add the external URL in the config on boot

The config already adds the external URL to the boot right? What do you mean by a propper fix, maybe you can create a merge request so that I know what you mean?

**Comment by grunjol** [comment]
The standard config doesn't add the external URL to the http/allowed_origins param at boot time. The config set a proper CORS header allowing the https calls from the web UI.
Need to investigate how to get the external URL config from the addon to set it automatically and not force the user to guess why can not access if its accessed to make a PR.
