### ISSUE TITLE
Mopidy API on 6680 port

### ISSUE THREAD

**Issue by Ripper2909** [hassio-addons/addon-mopidy#158]
# Problem/Motivation

Hi Frenck ! Thanks for this great addon, which works fine on my Intel NUC running HassOS.
I'm able to integrate it as media_player with the MPD integration (port 6600, as default), but I'm not able to reach the Mopidy API on the 6680 port.
I'd like the ability to reach the Mopidy API on the 6680 port in order to use this custom integration https://community.home-assistant.io/t/media-player-platform-for-mopidy/265836 which basically allows to browse the Mopidy library and display artworks in its media_player. 

## Expected behavior

I talked about it with the maker of the custom integration, who said that the Mopidy API port is needed, not the MPD one.

## Actual behavior

Only the Mopidy MPD port is configurable in the HA Mopidy add-on configuration tab :
![image](https://user-images.githubusercontent.com/1152891/128639068-9cfe5bcd-8f14-42ae-b1d6-3ec14add6b53.png)

## Steps to reproduce

Integration this https://github.com/bushvin/hass-integrations through HACS, and then not being able to integrate it :
![image](https://user-images.githubusercontent.com/1152891/128639074-2fceb1ce-a354-47a2-a25b-d09176687fd4.png)

## Proposed changes

Being able to set a Mopidy API port in the HA Mopidy add-on configuration tab, which will allow the use of the custom integration.
Here are the latest messages about it on the dedicated custom integration thread : https://community.home-assistant.io/t/media-player-platform-for-mopidy/265836/161

Hope you'll consider it. :) anyway, thanks for reading !

**Comment by Ripper2909** [comment]
Up please :)

**Comment by Paul-Vdp** [comment]
+1 ! Would be a modest but very useful enhancement.

**Comment by bushvin** [comment]
I concur. This would be useful!

**Comment by Ripper2909** [comment]
Any news on this please ? 😊

**Comment by Paul-Vdp** [comment]
Please ?
This lack is a total showstopper, preventing us all from using @bushvin's far superior Mopidy Media Player

**Comment by bushvin** [comment]
@Ripper2909 , @Paul-Vdp 
I've had a look at this addon, and @frenck correct me if I'm wrong...
port 80 is disabled by default, but is actually linked to the Mopidy http extension.
So, redirecting port 80 to 6680 on the (Network) configuration page of this add-on should do the trick.
Or alternatively you can set it to another port, but then you'd need to configure the port correctly using my integration.

I cannot test this on my setup at the moment, but please let me know if this solved your issue...
