### ISSUE TITLE
libffi error for spotify?

### ISSUE THREAD

**Issue by horstefan** [hassio-addons/addon-mopidy#187]
# Problem/Motivation

Extension spotify failed during setup. This might have left the registry in a bad state.

## Expected behavior

spotify module should load

## Actual behavior

spotify module fails with error:
SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)

## Steps to reproduce

Fresh install of HASSIO plugin mopidy

## Proposed changes

Looks like libffi-dev is removed in dockerfile while still required?

**Comment by oleging** [comment]
Spotify module didn't start on hassos 6.6 with the same reason.
