### ISSUE TITLE
Mopidy "not compatible with the processor of your device or the operating system you have installed on your device"

### ISSUE THREAD

**Issue by ByteMavericks** [hassio-addons/addon-mopidy#190]
Mopidy will not install on Core 2021-12-8 / Supervisor 2021.12.2 

Error message is "This add-on is not compatible with the processor of your device or the operating system you have installed on your device."

Have added edge repository, and am trying to install.  Cannot get any further than holding page, install is greyed out.

System log entry is
22-01-09 21:13:20 ERROR (MainThread) [supervisor.addons] Add-on 40817795_mopidy not supported on this platform

**Comment by ByteMavericks** [comment]
From looking at the docker file, it seems to require amd64 which would explain it not working on Pi - is this by design?

**Comment by frenck** [comment]
It only works on amd64, which is documented as such as well.

**Comment by ByteMavericks** [comment]
Apologies Frenck, I didn't see that and can't see where it's documented. Thanks for the update
