### ISSUE TITLE
Mopidy-Spotify extension is not running

### ISSUE THREAD

**Issue by Paytrix** [hassio-addons/addon-mopidy#195]
# Problem

Spotify extension seems to not be installed

## Expected behavior

Spotify extension should get started with 
```
- name: spotify/enabled
    value: 'true'
```
setting enabled.

## Actual behavior

Getting `Mopidy-Spotify extension is not running - you will not be able to play any Spotify tracks` message in Settings->Spotify

**Comment by litinoveweedle** [comment]
Having same issue. I have same old addon configuration and I used web oauth Iris function to re-login to my spotify account. Even so I still get same error message ('Mopidy-Spotify extension is not running - you will not be able to play any Spotify tracks') and I am unable to use Spotify.

**Comment by elginagain** [comment]
My error log is showing the same as yours @litinoveweedle. Did anyone here ever make any headway with this problem?

Is there anything I can do to assist with troubleshooting as far as testing things out or more error log info?

```
ERROR    2022-04-20 18:03:04,390 [391:MainThread] mopidy.__main__
  Extension spotify failed during setup. This might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/__main__.py", line 129, in main
    extension.setup(registry)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/__init__.py", line 49, in setup
    from mopidy_spotify.backend import SpotifyBackend
  File "/usr/local/lib/python3.7/dist-packages/mopidy_spotify/backend.py", line 8, in <module>
    import spotify
  File "/usr/local/lib/python3.7/dist-packages/spotify/__init__.py", line 95, in <module>
    from spotify.album import *  # noqa
  File "/usr/local/lib/python3.7/dist-packages/spotify/album.py", line 380, in <module>
    @serialized
SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
```
