### ISSUE TITLE
Installing This addon on Raspberry PI 4B

### ISSUE THREAD

**Issue by Doggolover69** [hassio-addons/addon-mopidy#210]
It appears that this addon is not supported on raspi or any other arm based systems. It appears greayed out in the addon menu and there is no way i can find install it.

Is it possible, as i understand this is written in python, to change a config file in order to allow this addons install on pis or any other arm machine as they are very popular for running HA.

**Comment by frenck** [comment]
> It appears that this addon is not supported on raspi or any other arm based systems.

That is correct. The add-on is only published for x86. It needs system dependencies which have been almost impossible to maintain for arm architectures, hence it isn't published for that platform.

../Frenck

**Comment by Doggolover69** [comment]
I was wondering, as mopidy is avalble on arm devices, why it cannot work as an addon in homeassistant?

**Comment by frenck** [comment]
Because the add-on isn't available on arm devices, the reason as mentioned in my previous response.

**Comment by Doggolover69** [comment]
I understand this is an intentional descsion but what dependencys are required to run it as an addon but not natively ?

**Comment by frenck** [comment]
I'm not understanding that question.
