### ISSUE TITLE
Add Icecast2 port mapping

### ISSUE THREAD

**Issue by RichieRich69** [hassio-addons/addon-mopidy#37]
# Problem/Motivation

> When switching on the Icecast2 feature the url is not accessible due to the port not being exposed by the docker container.

## Expected behavior

> Expect the port to be configurable on supervisor.

## Actual behavior

> No port can be configured for Icecast when setting up the addon

## Steps to reproduce

> Navigate to Mopidy Iris UI, select settings. Select Icecast click enable the navigate to the specified URL

## Proposed changes

> Adding the mappable port in the Mopidy Configuration page. I would like to contribute more to the community, so it would be great to know where I can start after cloning the repo.

**Comment by brammittendorff** [comment]
Hi there @RichieRich69 this is not an issue with the port.
Icecast or icecast2 is not build in with mopidy and/or iris.

The thing is you should run your own icecast server on port 8000 (https://www.icecast.org/docs/icecast-trunk/basic_setup/), or write an hassio addon that does it, or buy an icecast server on the internet and set that as your streaming endpoint.
