### ISSUE TITLE
latest addon version is not available at dockerhub hassioaddons/mopidy-amd64

### ISSUE THREAD

**Issue by litinoveweedle** [hassio-addons/addon-mopidy#39]
# Problem/Motivation

> Can't ugrade Hassio addon to the latest one (based on mopidy 3.50.0). Tried also reinstall but only older version of addon (based on Mopidy 3.49.0) is available for install via Hassio addon store on amd64 arch

## Expected behavior

> Updated addon version (based on Mopidy 3.50.0) is available for install at Hassio addon store

## Actual behavior

> Latest addon update is not available via Hassio addon store

## Steps to reproduce

> Try to update Mopidy Hassio addon via addon store

## Proposed solution

> please rebuild amd64 docker container based on latest addon github code 

20-07-15 11:24:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
20-07-15 11:24:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/hassio-addons repository
20-07-15 11:24:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/synesthesiam/hassio-addons repository
20-07-15 11:24:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/raph2i/hassio-addons repository
20-07-15 11:24:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository-edge repository
20-07-15 11:24:37 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/agileek/hassio-addons repository
20-07-15 11:24:38 INFO (MainThread) [supervisor.store] Load add-ons from store: 122 all - 0 new - 0 remove
20-07-15 11:25:21 INFO (SyncWorker_22) [supervisor.docker.interface] Stop addon_40817795_mopidy application
20-07-15 11:25:23 INFO (SyncWorker_22) [supervisor.docker.interface] Clean addon_40817795_mopidy application
20-07-15 11:25:23 INFO (SyncWorker_22) [supervisor.docker.interface] Remove image hassioaddons/mopidy-amd64 with latest and 06fcfd1
20-07-15 11:25:24 INFO (MainThread) [supervisor.addons.addon] Remove add-on data folder /data/addons/data/40817795_mopidy
20-07-15 11:25:24 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 40817795_mopidy
20-07-15 11:25:24 INFO (MainThread) [supervisor.addons] Add-on '40817795_mopidy' successfully removed
20-07-15 11:25:37 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/40817795_mopidy
20-07-15 11:25:37 INFO (SyncWorker_26) [supervisor.docker.interface] Pull image hassioaddons/mopidy-amd64 tag 06fcfd1.
20-07-15 11:26:08 INFO (MainThread) [supervisor.addons] Add-on '40817795_mopidy' successfully installed
20-07-15 11:26:24 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for 40817795_mopidy

<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository">hassio-addons/repository</a></strong></div><div>Home Assistant Community Add-ons. Contribute to hassio-addons/repository development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/13844975?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/home-assistant/hassio-addons">home-assistant/hassio-addons</a></strong></div><div>:heavy_plus_sign: Docker add-ons for Home Assistant - home-assistant/hassio-addons</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/2743976?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/synesthesiam/hassio-addons">synesthesiam/hassio-addons</a></strong></div><div>My Hass.IO add-ons. Contribute to synesthesiam/hassio-addons development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars3.githubusercontent.com/u/55005474?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/raph2i/hassio-addons">raph2i/hassio-addons</a></strong></div><div>some Hass.IO Addons. Contribute to raph2i/hassio-addons development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars1.githubusercontent.com/u/30772201?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/hassio-addons/repository-edge">hassio-addons/repository-edge</a></strong></div><div>EDGE - Home Assistant Community Add-ons. Contribute to hassio-addons/repository-edge development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/8244644?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/agileek/hassio-addons">agileek/hassio-addons</a></strong></div><div>Contribute to agileek/hassio-addons development by creating an account on GitHub.</div></blockquote>

**Comment by frenck** [comment]
The add-on has no versions, as it has never been released.

https://github.com/hassio-addons/addon-mopidy/releases
