### ISSUE TITLE
No Connection from Mopidy to Snapcast when using Hassio with SSL

### ISSUE THREAD

**Issue by cjuma** [hassio-addons/addon-mopidy#46]
I'm running my Hassio Instance with SSL. The Mopidy Addon works great so far but it was not possible to establish a connection to the snapcast server. Neither to the snapcast server on the same hassio instane or antoher instance in my LAN.

My other Instance (Debian Server) running without SSL, so i give it a try an disabled SSL for the hassio. After that, mopidy directly connected to the hassio snapcast server and the other snapcast server on my debian machine.

I'm not sure if it is just a Problem from the AddOn or a mopidy problem.
In a normal mopidy instance your not able to switch to ssl connection because iris is using the http extension where are no options to enabeld ssl.

So my question now: Is there a way to establish a connection between mopidy an snapcast with activated ssl for hassio?
Maybe with the ip from the docker snapcast container? Does anybody got that two Addons running in this way?

General Infos:
Mopidy Addon from this repo
Snapcast Server from this repo: https://github.com/raph2i/hassio-addons
HassOS 4.12 in a VM

**Comment by frenck** [comment]
This add-on does not support snapcast.
