### ISSUE TITLE
nginx version problems

### ISSUE THREAD

**Issue by realthk** [hassio-addons/addon-mopidy#51]
# Problem/Motivation
Cannot build addon docker 

## Actual behavior
Apt install fails with these 2 errors:
```
E: Version '1.14.2-2+deb10u1' for 'libnginx-mod-http-lua' was not found
E: Version '1.14.2-2+deb10u1' for 'nginx' was not found
```

## Steps to reproduce
Either try to install under Supervisor local-addon, or do a docker build anywhere

## Proposed changes
I don't know what should be the correct version for these, just tried apt install without version for these 2, and it succeeded.

**Comment by frenck** [comment]
Add-ons are distributes pre-build in the add-on repositories.

If you are into building it yourself, it is assumed you know what to do.

**Comment by realthk** [comment]
Fine, I did, but why leave an outdated Dockerfile in the repo?

**Comment by frenck** [comment]
Because there is more work to do and it will be picked up on the next cycle? (as this is not published as a stable add-on it has lower priority).

I'm not sure what your problem is?

**Comment by realthk** [comment]
Because it is a frequent and understandable wish to use the audio output of the PC running Home Assistant and this addon seems to be the only option for that purpose (especially since HA Supervised grabs hold of PulseAudio, so by design it does not allow the host to run MPD correctly as it won't have sound output...)

Maybe a roadmap would ease the mind of helpless users who'd like to solve this issue, if it was known it probably takes just a couple of months and HA will have an official local media player addon.

**Comment by frenck** [comment]
If you want a roadmap, please use a commercial product.

**Comment by katonage** [comment]
There are many contributions dispersed on github about HA audio. Maybe some "advertisement" could direct contributors helping hands here (if top minds think this is the addon togo).
