### ISSUE TITLE
Any timeline for arm support?

### ISSUE THREAD

**Issue by motionthings** [hassio-addons/addon-mopidy#73]
# Problem/Motivation

> Most people run Hassio on Raspberry Pi's?

## Expected behavior

> I was hoping this would work as an addon in Hassio on a Raspberry Pi.

## Actual behavior

> It does not work on arm processors.

## Steps to reproduce

> It can not be installed on any arm based architecture cpu's.

## Proposed changes

> Please make it work on Raspberry Pi's
> Many people would like this?

I saw that you closed the same issue almost a year ago.
Has anything gotten better?

**Comment by frenck** [comment]
Arm support has been removed and will not be added back
