### ISSUE TITLE
Addon not listed in Hassio?

### ISSUE THREAD

**Issue by Romkabouter** [hassio-addons/addon-mopidy#8]
# Problem/Motivation

> I found this addon via a google search, but in Hassio I cannot see the it under the community addons

## Expected behavior

> Mopidy listed under addons

## Actual behavior

> Not listed
## Steps to reproduce

> Open Hassio, go to addons and "add-on store". Check Community Hass.io Add-ons for Mopidy

**Comment by Romkabouter** [comment]
ok, apparently not an issue, but I had to include the edge repo.
Not very clearly document though

**Comment by ludeeus** [comment]
It has not yet been released to stable, that's why :)

**Comment by Romkabouter** [comment]
Yes, I was not aware. Sorry about that. 
Since it is not stable, is it possible to add snapcast server into this add-on?
I am now running this add-on: https://github.com/bestlibre/hassio-addons/tree/master/mopidy_cast next to mopidy, but rather have it integrated.

Thnx
