### ISSUE TITLE
access to Mopidy HTTP API

### ISSUE THREAD

**Issue by litinoveweedle** [hassio-addons/addon-mopidy#98]
# Problem/Motivation

While Mopidy/Iris could be managed by external (for example mobile) app via MPD interface, this is not optimal due to incomplete Mopidy MPD implementation. Therefore it would be great to have possibility to use Mopidy HTTP API control interface as well. (for example by Mopidy Mobile Android app). I tried to use Network configuration for Mopidy addon to map "Web interface" but I think it is IRIS interface, not Mopidy HTTP API.

## Expected behavior

Be able to use Mopidy HTTP API interface which should be available/mapped to HA available IP. 

## Actual behavior

Could not use Mopidy HTTP API

## Steps to reproduce

Try to control Mopidy via Android Mopidy Mobile app.

## Proposed changes

- allow to configure port mapping from container to HA for Mopidy HTTP API
- allow to configure user/passwd for Mopidy HTTP API (from other than localhost IPs)

**Comment by frenck** [comment]
The mapping is not needed, as add-on are internally accessible fully for Home Assistant. The hostname needed for that can be found in the add-on configuration page.
